//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GeneralYMS_SAS.App_Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Affairs
    {
        public int AffairId { get; set; }
        public string AffairName { get; set; }
        public string AffairCode { get; set; }
        public int AreaId { get; set; }
        public int WindowId { get; set; }
        public int ConnectLineId { get; set; }
        public string StateId { get; set; }
        public Nullable<int> ExpDays { get; set; }
        public string AffairPolicy { get; set; }
        public string AffairCondition { get; set; }
        public string AffairMaterial { get; set; }
        public string AffairFlow { get; set; }
        public Nullable<bool> Available { get; set; }
    }
}
