//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GeneralYMS_SAS.App_Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class AffairsInfo
    {
        public int AffairInfoId { get; set; }
        public int PersonId { get; set; }
        public Nullable<int> TransactType { get; set; }
        public int AffairId { get; set; }
        public int OperatorId { get; set; }
        public Nullable<System.DateTime> BeginTransTime { get; set; }
        public Nullable<System.DateTime> LastTransTime { get; set; }
        public string AffairInfoCode { get; set; }
        public Nullable<int> StateId { get; set; }
        public Nullable<int> NextFlowOperatorId { get; set; }
        public string AffairDescription { get; set; }
        public Nullable<int> IsFinish { get; set; }
        public string QueueNum { get; set; }
        public string SatisfyDegree { get; set; }
        public string Memo { get; set; }
        public Nullable<bool> Available { get; set; }
    }
}
