//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GeneralYMS_SAS.App_Data
{
    public partial class AttatchFile
    {
        public int AttatchFileId { get; set; }
        public int AffairInfoId { get; set; }
        public string AttatchFileName { get; set; }
        public byte[] AttatchFileContent { get; set; }
    }
}
