//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GeneralYMS_SAS.App_Data
{
    using System;

    public partial class LineConfig
    {
        public int LineConfigId { get; set; }
        public int AffairLineId { get; set; }
        public int AreaId { get; set; }
        public string LineAppName { get; set; }
        public string LineAppUrl { get; set; }
        public string LineAppClassName { get; set; }
        public string LineAppWindowName { get; set; }
        public string LineAppUserNameClass { get; set; }
        public string LineAppPasswordClass { get; set; }
        public string LineAppLoginBtnClass { get; set; }
        public string LineAppLoginBtnName { get; set; }
        public Nullable<bool> Available { get; set; }
    }
}
