//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GeneralYMS_SAS.App_Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class YmsDb : DbContext
    {
        public YmsDb()
            : base("name=YmsDb")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<AffairLine> AffairLine { get; set; }
        public DbSet<Affairs> Affairs { get; set; }
        public DbSet<AffairsInfo> AffairsInfo { get; set; }
        public DbSet<Area> Area { get; set; }
        public DbSet<AttatchFile> AttatchFile { get; set; }
        public DbSet<Dic_Education> Dic_Education { get; set; }
        public DbSet<Dic_Nation> Dic_Nation { get; set; }
        public DbSet<LineConfig> LineConfig { get; set; }
        public DbSet<Notice> Notice { get; set; }
        public DbSet<PersonBase> PersonBase { get; set; }
        public DbSet<States> States { get; set; }
        public DbSet<UserList> UserList { get; set; }
        public DbSet<UserRole> UserRole { get; set; }
        public DbSet<Window> Window { get; set; }
        public DbSet<WorkGroup> WorkGroup { get; set; }
    }
}
