//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GeneralYMS_SAS.App_Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Notice
    {
        public int NoticeId { get; set; }
        public string PublishUser { get; set; }
        public Nullable<System.DateTime> PublishTimer { get; set; }
        public string NoticeTitle { get; set; }
        public string NoticeContent { get; set; }
        public int AreaId { get; set; }
        public Nullable<bool> Available { get; set; }
    }
}
