//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GeneralYMS_SAS.App_Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class PersonBase
    {
        public int PersonId { get; set; }
        public string PersonName { get; set; }
        public Nullable<int> CertTypeId { get; set; }
        public string CertCode { get; set; }
        public string Gender { get; set; }
        public string Birthday { get; set; }
        public Nullable<int> EducationId { get; set; }
        public Nullable<int> NationId { get; set; }
        public string Address { get; set; }
        public string ZipCode { get; set; }
        public string ContactAddress { get; set; }
        public string WorkAddress { get; set; }
        public string Phone { get; set; }
        public Nullable<System.DateTime> RegisterTime { get; set; }
    }
}
