//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GeneralYMS_SAS.App_Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserList
    {
        public int UserId { get; set; }
        public string UserName { get; set; }
        public string UserPass { get; set; }
        public string UserRealName { get; set; }
        public int UserAreaId { get; set; }
        public int UserRoleId { get; set; }
        public string Gender { get; set; }
        public string DeptName { get; set; }
        public string HeadShip { get; set; }
        public string JobNum { get; set; }
        public string UserPhone { get; set; }
        public string UserEmail { get; set; }
        public string UserIp { get; set; }
        public string Memo { get; set; }
        public Nullable<System.DateTime> LastLoginTime { get; set; }
        public Nullable<bool> Available { get; set; }
    }
}
